// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteVot.Data;

namespace WebsiteVot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231218074912_crdb")]
    partial class crdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebsiteVot.Models.Cthoadon", b =>
                {
                    b.Property<int>("MaCthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaCTHD")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("MaHd")
                        .HasColumnName("MaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaMh")
                        .HasColumnName("MaMH")
                        .HasColumnType("int");

                    b.Property<short?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaCthd")
                        .HasName("PK__CTHOADON__1E4FA7717DD72FDA");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaMh");

                    b.ToTable("CTHOADON");
                });

            modelBuilder.Entity("WebsiteVot.Models.Cuahang", b =>
                {
                    b.Property<int>("MaCh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaCH")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DienThoai")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaCh")
                        .HasName("PK__CUAHANG__27258E009237B679");

                    b.ToTable("CUAHANG");
                });

            modelBuilder.Entity("WebsiteVot.Models.Danhmuc", b =>
                {
                    b.Property<int>("MaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaDM")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaDm")
                        .HasName("PK__DANHMUC__2725866E85E35D0A");

                    b.ToTable("DANHMUC");
                });

            modelBuilder.Entity("WebsiteVot.Models.Hoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaHD")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaNd")
                        .HasColumnName("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("MaHd")
                        .HasName("PK__HOADON__2725A6E006A772C2");

                    b.HasIndex("MaNd");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("WebsiteVot.Models.Mathang", b =>
                {
                    b.Property<int>("MaMh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaMH")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("GiaGoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int?>("LuotMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("LuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("MaDm")
                        .HasColumnName("MaDM")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<short?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaMh")
                        .HasName("PK__MATHANG__2725DFD96AD3FF4C");

                    b.HasIndex("MaDm");

                    b.ToTable("MATHANG");
                });

            modelBuilder.Entity("WebsiteVot.Models.Nguoidung", b =>
                {
                    b.Property<int>("MaNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaND")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("DienThoai")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("MatKhau")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PhanQuyen")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaNd")
                        .HasName("PK__NGUOIDUN__2725D724CD5F6F51");

                    b.ToTable("NGUOIDUNG");
                });

            modelBuilder.Entity("WebsiteVot.Models.Cthoadon", b =>
                {
                    b.HasOne("WebsiteVot.Models.Hoadon", "MaHdNavigation")
                        .WithMany("Cthoadon")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK__CTHOADON__MaHD__239E4DCF")
                        .IsRequired();

                    b.HasOne("WebsiteVot.Models.Mathang", "MaMhNavigation")
                        .WithMany("Cthoadon")
                        .HasForeignKey("MaMh")
                        .HasConstraintName("FK__CTHOADON__MaMH__24927208")
                        .IsRequired();
                });

            modelBuilder.Entity("WebsiteVot.Models.Hoadon", b =>
                {
                    b.HasOne("WebsiteVot.Models.Nguoidung", "MaNdNavigation")
                        .WithMany("Hoadon")
                        .HasForeignKey("MaNd")
                        .HasConstraintName("FK__HOADON__MaND__1FCDBCEB")
                        .IsRequired();
                });

            modelBuilder.Entity("WebsiteVot.Models.Mathang", b =>
                {
                    b.HasOne("WebsiteVot.Models.Danhmuc", "MaDmNavigation")
                        .WithMany("Mathang")
                        .HasForeignKey("MaDm")
                        .HasConstraintName("FK__MATHANG__MaDM__173876EA")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
